version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: currency_stats
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      - "6380:6380" # Expose Redis Streams port

# Add any additional configuration for Redis Streams here if needed
